version: 2.1
commands:
  npm-ci:
    description: "npm ci with cache"
    parameters:
      prefix:
        type: string
      path:
        type: string
    steps:
      - restore_cache:
          key: << parameters.name >>-{{ checksum "<< parameters.path >>/package-lock.json" }}
      - run:
          command: ADBLOCK=true npm ci
          working_directory: << parameters.path >>
      - save_cache:
          key: << parameters.name >>-{{ checksum "<< parameters.path >>/package-lock.json" }}
          paths:
            - << parameters.path >>/node_modules
executors:
  ionic-app:
    docker:
      - image: circleci/node:10
    working_directory: ~/hackernews-graphql
jobs:
  build:
    executor: ionic-app
    steps:
      - checkout
      - npm-ci:
          prefix: ionic-app
          path: ~/hackernews-graphql/ionic-app/
      - run:
          command: npm run build
          working_directory: ~/hackernews-graphql/ionic-app
  test:
    executor: ionic-app
    steps:
      - checkout
      - npm-ci:
          prefix: ionic-app
          path: ~/hackernews-graphql/ionic-app/
      - run:
          command: npm test
          working_directory: ~/hackernews-graphql/ionic-app

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
