version: 2.1
executors:
  ionic-app:
    docker:
      - image: circleci/node:10
    working_directory: ~/hackernews-graphql
jobs:
  build:
    executor: ionic-app
    steps:
      - checkout
      - restore_cache:
          key: ionic-app-{{ checksum "~/hackernews-graphql/ionic-app/package-lock.json" }}
      - run:
          command: ADBLOCK=true npm ci
          working_directory: ~/hackernews-graphql/ionic-app
      - save_cache:
          key: ionic-app-{{ checksum "~/hackernews-graphql/ionic-app/package-lock.json" }}
          paths:
            - ~/hackernews-graphql/ionic-app/node_modules
      - run:
          command: npm run build
          working_directory: ~/hackernews-graphql/ionic-app
  test:
    executor: ionic-app
    steps:
      - checkout
      - restore_cache:
          key: ionic-app-{{ checksum "~/hackernews-graphql/ionic-app/package-lock.json" }}
      - run:
          command: ADBLOCK=true npm ci
          working_directory: ~/hackernews-graphql/ionic-app
      - save_cache:
          key: ionic-app-{{ checksum "~/hackernews-graphql/ionic-app/package-lock.json" }}
          paths:
            - ~/hackernews-graphql/ionic-app/node_modules
      - run:
          command: npm test
          working_directory: ~/hackernews-graphql/ionic-app
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
