version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/hackernews-graphql/ionic-app
    steps:
      - checkout
      - run: ADBLOCK=true npm ci
      - run: npm run build
  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/hackernews-graphql/ionic-app
    steps:
      - checkout
      - run: ADBLOCK=true npm ci
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
