name: Build and Push
on:
  push
  # push:
  # branches:
  #   - master
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker Image
        uses: actions/docker/cli@master
        env:
          CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
        with:
          args: >
            build -t gcr.io/hackernews-252716/app:latest . \
              --build-arg VCS_REF=${{ github.sha }} \
              --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Setup Google Cloud
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

      - name: Setup Docker Registry to GCR
        uses: actions/gcloud/cli@master
        with:
          args: >
            auth configure-docker --quiet

      - name: Push Docker Image to GCR
        uses: actions/docker/cli@master
        with:
          args: >
            push gcr.io/hackernews-252716/app:latest
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
