name: Flutter Web
on:
  push:
    paths:
      - "flutter_app/*"
      - ".github/workflows/flutter.yml"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.9.x"
          channel: "dev"
      - name: Enable flutter-web
        run: flutter config --enable-web
      - name: Get packages
        run: flutter pub get
        working-directory: flutter_app
      - name: Test
        run: flutter test
        working-directory: flutter_app
      - name: Build
        run: flutter build web
        working-directory: flutter_app
