name: Flutter Web
on:
  push:
    paths:
      - "hn_app/*"
      - ".github/workflows/flutter.yml"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.9.x"
          channel: "dev"
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web
